# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d7a0d12b-fb94-4795-996c-aac800517ab1";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-428e63c6-f7bb-4e32-94af-cea7ad71bc51".device = "/dev/disk/by-uuid/428e63c6-f7bb-4e32-94af-cea7ad71bc51";
  boot.initrd.luks.devices."luks-e701612f-d046-4505-8ea5-b7069222ae8c".device = "/dev/disk/by-uuid/e701612f-d046-4505-8ea5-b7069222ae8c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1B9C-2748";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6de14442-0c67-4342-94e2-e0b47dfb9fa2"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
